<a href="https://colab.research.google.com/github/RamonSantos10/ML-DSM/blob/main/AulaMachineLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introdução de Python

In [ ]:
print('Hello World!')

Hello World!

# Bibliotecas e Funções de Python

In [ ]:
import math

def equacao2grau(a,b,c):
  delta = b**2 - 4*a*c

  if(delta < 0):
    return 'Numero sem raiz', delta

  x1 = (-b + math.sqrt(delta)) / (2*a)
  x2 = (-b - math.sqrt(delta)) / (2*a)

  return x1,x2

eq = equacao2grau(1,-3,2)
print(eq)

import random
for i in range(5):
  a = random.randint(-5, 5)
  b = random.randint(-10, 10)
  c = random.randint(-10, 10)

  eq += equacao2grau(a, b, c)

for i in range(12):
  if(i % 2 == 0):
    if(eq[i] != 'Numero sem raiz'):
      print('X1: [', f"{eq[i]:.2f}",']')
  else:
    if(eq[i] != 'Numero sem raiz'):
      print('X2: [', f"{eq[i]:.2f}",'] \n')

(2.0, 1.0)
X1: [ 2.00 ]
X2: [ 1.00 ]

X1: [ -8.58 ]
X2: [ 0.58 ]

X2: [ -99.00 ]

X2: [ -124.00 ]

X2: [ -20.00 ]

X1: [ 2.00 ]
X2: [ -0.75 ]

# Diferenças de Profissões

### Analista de Dados
- Não mexe com código
### Cientista de Dados
- Mexe com código em notação científica (com no Google Colab)
### Enegenheiro de Dados
- Mexe com código, com o objetivo de montar toda infaestrutura do sistema

# Trabaçhando com dados externos

## Bibliotecas de uso da pipeline

In [ ]:
!pip -q install plotly
!pip -q install yellowbrick

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

## Básico Pandas

In [ ]:
base_credit = pd.read_csv('/content/credit_data.csv')
base_credit.head()

   clientid        income        age         loan  default
0         1  66155.925095  59.017015  8106.532131        0
1         2  34415.153966  48.117153  6564.745018        0
2         3  57317.170063  63.108049  8020.953296        0
3         4  42709.534201  45.751972  6103.642260        0
4         5  66952.688845  18.584336  8770.099235        1

In [ ]:
base_credit[base_credit['loan'] <= 1.377630]

     clientid        income        age     loan  default
865       866  28072.604355  54.142548  1.37763        0

In [ ]:
base_credit.describe()

          clientid        income          age          loan      default
count  2000.000000   2000.000000  1997.000000   2000.000000  2000.000000
mean   1000.500000  45331.600018    40.807559   4444.369695     0.141500
std     577.494589  14326.327119    13.624469   3045.410024     0.348624
min       1.000000  20014.489470   -52.423280      1.377630     0.000000
25%     500.750000  32796.459717    28.990415   1939.708847     0.000000
50%    1000.500000  45789.117313    41.317159   3974.719419     0.000000
75%    1500.250000  57791.281668    52.587040   6432.410625     0.000000
max    2000.000000  69995.685578    63.971796  13766.051239     1.000000

## Análise de Anomalia: **Idade Negativa**

In [ ]:
base_credit.loc[base_credit['age'] <= 0]

    clientid        income        age         loan  default
15        16  50501.726689 -28.218361  3977.287432        0
21        22  32197.620701 -52.423280  4244.057136        0
26        27  63287.038908 -36.496976  9595.286289        0

1. Extreminidade
2. Minoria
3. Relevância

Se o dado positivar em um dos 3 pontos, ele não pode ser removido, mas sim, normalizado